# Generated by Django 3.0.6 on 2020-07-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
